name: 'dart_parser'
version: 1.0.1
description: Dart parser

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  charcode: ^1.1.0
  path: '>=0.9.0 <2.0.0'
  yaml: ^2.1.2
  package_config: '>=0.1.5 <2.0.0'
dev_dependencies:
  build_runner: ^1.7.3
  build_web_compilers: ^2.8.0